services:
  postgres:
    image: postgres:16
    container_name: evstore-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: evuser
      POSTGRES_PASSWORD: evpassword
      POSTGRES_DB: evstore
    ports:
      - "5432:5432"
    volumes:
#      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
