package ge.evstore.ev_store.entity;

import jakarta.persistence.*;
import lombok.Data;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "orders") // “order” is a reserved word in SQL, so use “orders”
@Data
public class Order {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // A human‐readable order number (could be autogenerated, or e.g. UUID)
    @Column(name = "order_number", nullable = false, unique = true)
    private String orderNumber;

    @CreationTimestamp
    @Column(name = "order_date", nullable = false, updatable = false)
    private LocalDateTime orderDate;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private OrderStatus status;

    @Column(name = "total_price", nullable = false)
    private Double totalPrice;

    // Which user placed this order
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    private User user;

    @Column(length = 1000)
    private String specialInstructions;
    // The list of items in this order
    @OneToMany(
            mappedBy = "order",
            cascade = CascadeType.ALL,
            orphanRemoval = true
    )
    private List<OrderItem> items = new ArrayList<>();

    /** Utility to add an OrderItem and set its back-reference */
    public void addOrderItem(final OrderItem item) {
        items.add(item);
        item.setOrder(this);
    }
}